name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Need full git history for version detection

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Set up Python
      run: uv python install 3.11

    - name: Install dependencies
      run: uv sync

    - name: Run tests
      run: uv run pytest tests/ -v

    - name: Build package
      run: uv build

    - name: Check version
      run: |
        echo "Built version:"
        ls dist/
        # Verify we have a clean release version (no .dev or +local)
        python -c "
        import glob
        files = glob.glob('dist/*.whl')
        if files:
            filename = files[0]
            if '.dev' in filename or '+' in filename:
                print(f'ERROR: Development version detected: {filename}')
                exit(1)
            else:
                print(f'✓ Clean release version: {filename}')
        "

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.10.3
      with:
        verbose: true
        password: ${{ secrets.PYPI_API_TOKEN }}